#spring:
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    open-in-view: false
#    hibernate:
#      ddl-auto: 'create-drop'
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:


server:
  port : 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: user
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
